f.diff.broadcast <- function(chart,
                             ignore.types = c('lnotel')){
  #' For each row, gets the time before the next key
  #' 
  #' This will not overwrite the current columns,
  #' it will generate a separate one.
  #' 
  #' @param chart The **data.frame** generated by f.chart.sim
  #' @param ignore.lnotel A **logical** to determine if lnotel
  #' should be included in the broadcasting
  
  require(magrittr)
  require(reshape2)
  require(Rfast)
  
  # Drop NA rows
  chart <- subset(chart, !is.na(chart$types))
  
  # Ignores any types that matches the list
  chart$types[chart$types %in% ignore.types] <- NA
  
  # Cast keys to longer table.
  chart %<>% 
    dcast(offsets ~ keys, value.var = 'types')
  
  # The plan is to flip the chart up-side down, then 
  # we track different columns on the accumulated
  # offsets.
  chart <- chart[order(chart$offsets,decreasing = T),]

  # Grabs the number of keys in the chart
  keys <- ncol(chart) - 1
  
  # Diff trackers are variable that tracks all columns
  diff.trackers <- vector(mode = "numeric",
                          length = keys)
  
  # Append extra columns
  diff.columns <- data.frame(matrix(ncol=keys))
  diff.columns %<>% rename_all(paste0, ".diff")
  chart %<>% cbind(diff.columns)
  
  # This is the column to reference from
  col <- 2 
  offset.old <- 0
  for (row in 1:nrow(chart)){ 
    # Grab current row offset
    offset <- chart[row, 'offsets']
    
    diff.offset <- offset.old - offset
    diff.trackers <- diff.trackers + diff.offset
    
    # Assign current diffs
    chart[row, (col+keys):(col+2*keys-1)] <- diff.trackers
    
    # Reset Mask is to reset the difference once a note is
    # encountered
    reset.mask <- apply(chart[row, col:(col+keys-1)],
                        2, 
                        FUN=is.na)
    diff.trackers[!reset.mask] <- 0
    
    # Assign old offset
    offset.old <- offset
  }
  
  # This changes all negative numbers to -1
  # It is the result of checking diffs before a note happens
  chart[chart < 0] <- -1
  
  # We will convert it into a long table
  # Melt by original keys
  chart %<>% 
    melt(measure.vars = 2:8,
         variable.name = 'keys',
         value.name = 'types',
         na.rm = T)
  
  chart$keys %<>%
    as.numeric()
  
  # Melt by diffs
  chart %<>% 
    melt(measure.vars = 2:8,
         variable.name = 'diff.types',
         value.name = 'diffs',
         na.rm = T)
  
  chart$diff.types %<>%
    regmatches(regexpr("[[:digit:]]+", .)) %>% 
    as.numeric()
  
  return(chart)
}
