f.stress.tf <- function(chart,
                        tf.groups){
  #' Transfers stress to other keys
  #' 
  #' @description Depending on the function provided,
  #' stress transfer may vary. However, in most cases
  #' these stress transfers are assumptions on playstyle
  #' 
  #' This will not overwrite the current stress columns,
  #' it will generate a separate one.
  #' 
  #' @param chart The **data.frame** generated by f.chart.sim
  #' @param tf.groups A **list** of key groups to have internal
  #' stress transfer. There's a specific format to use.
  #' 
  #' @examples 
  #' This is the format required for `tf.groups`
  #' `list(vector.numeric.1, vector.numeric.2, ..., FUN=fun)`
  #' 
  #' For example, if we want to group 1:3 and 4:7.
  #' `list(c(1,2,3), c(4,5,6,7), FUN=fun)`
  #' 
  #' The example also has a specific format
  #' `function(stress.main, stress.others){ return(stress.main) }`
  #' `stress.main` is the current key's stress value
  #' `stress.others` is the other key's stress values
  #' 
  #' The function must return the stress value.
  #'  
  

  
}