f.stress.sim <- function(chart,
                         f.spike,
                         f.decay,
                         df.mapping,
                         stress.init = 0.0){
  #' Simulates the stress
  #' 
  #' @description 
  #' 
  #' @param chart Chart generated by `f.stress.mapper`
  #' @param f.spike A **Function** to dictate how stress
  #' should change upon encountering different types
  #' 
  #' The function **must** have a 'stress' argument.
  #' The function **must** return the new 'stress' value
  #' 
  #' Note: Arguments used in the function should be
  #' the exact same name as the ones used in stress
  #' mapper
  #' 
  #' @param f.decay A **Function** to dictate how stress
  #' should change during idle.
  #' 
  #' The function must have both 'stress' and 
  #' 'duration' arguments.
  #' The function must return the new 'stress' value
  #' 
  #' Note: 'duration' is measured in **ms**. There are no
  #' custom arguments.
  #' 
  #' @param df.mapping A 'mapping' **data.frame** to 
  #' indicate what constants to use for `f.spike`.
  #' 
  #' The table must contain the column 'types', with
  #' rows: 'note', 'lnoteh', 'lnotel'.
  #' This can be used as the base template
  #' `data.frame(types = c("note", "lnoteh", "lnotel"))`
  #'
  #' Note: Extra column names must be named exactly
  #' the same as arguments in `f.spike`
  #' 
  #' @param stress.init The **numeric** of 'stress' to 
  #' initialize the simulation with
  #' 
  #' 
   
  require(magrittr)
  require(dplyr)
  
  # Some test data
  # chart <- data.frame(keys = c(1,2,3,4),
  #                     types = c('note', 'lnoteh', 'lnotel', 'note'),
  #                     offsets = c(10,20,30,40))
  # 
  # df.mapping <- data.frame(types = c('note', 'lnoteh', 'lnotel'),
  #                          adds = c(50,50,25),
  #                          mults = c(1.1, 1.1, 1.03))
  # 
  # 
  # f.spike <- function(stress, args){
  #   return((stress + args$adds) * args$mults)
  # }
  # f.decay <- function(stress, duration){
  #   return(stress / (2 ** duration))
  # }
  
  # Firstly, we join the mapping with the chart
  chart %<>% merge(df.mapping, by='types')
  
  # These are the column indexes of the custom arguments
  args.columns = 4:(ncol(chart))
  
  # Allocate columns in advance
  chart$stress.spike <- NA
  chart$stress.decay <- NA
  
  # We will be looping through the chart by key
  chart.k <- split(x = chart, f = chart$keys)
  for (key in 1:length(chart.k)){
    stress = 0
    offset.old = 0
    
    for (row in 1:nrow(chart.k[[key]])) {
      # This extracts all user defined columns as a list with named
      # arguments.
      args <- as.list(chart.k[[key]][row, args.columns])
      
      # Current offset
      offset.new <- as.numeric(chart[row, "offsets"])
      
      # Calculate decay then assign to dataframe
      stress <- f.decay(stress, offset.new - offset.old)
      stress <- max(stress, 0) # Stress will not go below 0
      chart.k[[key]][row, "stress.decay"] <- stress
      
      # Calculate spike then assign to dataframe
      stress <- f.spike(stress, args)
      chart.k[[key]][row, "stress.spike"] <- stress
      
      # Update new offset
      offset.old <- chart[row, "offsets"]
    }
  }
  
  # Join split chart into 1
  chart <- bind_rows(chart.k)
  return(chart)
}
