f.stress.sim <- function(chart,
                         f.spike,
                         f.decay,
                         df.mapping,
                         stress.init = 0.0){
  #' Simulates the Stress through types
  #' 
  #' @description 
  #' 
  #' @param chart Chart generated by `f.stress.mapper`
  #' @param f.spike A **Function** to dictate how stress
  #' should change upon encountering different types
  #' 
  #' The function **must** have 'stress' and 'args'
  #' arguments.
  #' The function **must** return the new 'stress' value
  #' 
  #' Note: Arguments used in the function should be
  #' the exact same name as the ones used in stress
  #' mapper
  #' 
  #' @param f.decay A **Function** to dictate how stress
  #' should change during idle.
  #' 
  #' The function must have both 'stress' and 
  #' 'duration' arguments.
  #' The function must return the new 'stress' value
  #' 
  #' Note: 'duration' is measured in **ms**. There are no
  #' custom arguments.
  #' 
  #' @param df.mapping A 'mapping' **data.frame** to 
  #' indicate what constants to use for `f.spike`.
  #' 
  #' The table must contain the column 'types', with
  #' rows: 'note', 'lnoteh', 'lnotel'.
  #' This can be used as the base template
  #' `data.frame(types = c("note", "lnoteh", "lnotel"))`
  #'
  #' Note: Extra column names must be named exactly
  #' the same as arguments in `f.spike`
  #' 
  #' @param stress.init The **numeric** of 'stress' to 
  #' initialize the simulation with
   
  require(magrittr)
  require(dplyr)
  require(Rcpp)
  
  Rcpp::sourceCpp("src/cpp/stress_sim.cpp")
  
  # Firstly, we join the mapping with the chart
  chart %<>% merge(df.mapping, by='types')
  
  # These are the column indexes of the custom arguments
  args.columns = 4:(ncol(chart))
  
  # Allocate columns in advance
  chart %<>% 
    arrange(offsets)
  
  args <- split(df.mapping, df.mapping$types)
  
  
  "Chart Frame is used to fill in those missing values 
  generated by columns on different offsets.
  
  This is used to do a OUTER JOIN to each key groups,
  hence you get NA data on those rows that shouldn't
  have data."
  chart.frame <- data.frame(offsets=unique(chart$offsets))
  
  # We will be looping through the chart by key
  chart.k.split <- split(x = chart, f = chart$keys)
  for (key in 1:length(chart.k.split)){
    key = 1
    chart.k <- chart.k.split[[key]]
    chart.k %<>%
      merge(chart.frame, by='offsets', all=T) %>% 
      mutate(is.spike = !is.na(types))
    
    simulate_key(
      chart.k$offsets,
      chart.k$types,
      args,
      f.stress.spike,
      f.stress.decay
    )
    
    chart.k %<>% mutate(keys = key)
    
    
    chart.k.split[[key]] <- chart.k
  }
  
  # Join charts of different keys into one
  chart <- bind_rows(chart.k.split)
  chart %<>%
    mutate(stress = pmax(stress.spike, stress.decay, na.rm = T))
  return(chart)
}

# Some test data
# chart <- data.frame(keys = c(1,2,3,4),
#                     types = c('note', 'lnoteh', 'lnotel', 'note'),
#                     offsets = c(10,20,30,40))
# 
# df.mapping <- data.frame(types = c('note', 'lnoteh', 'lnotel'),
#                          adds = c(50,50,25),
#                          mults = c(1.1, 1.1, 1.03))
# 
# 
# f.spike <- function(stress, args){
#   return((stress + args$adds) * args$mults)
# }
# f.decay <- function(stress, duration){
#   return(stress / (2 ** duration))
# }
