f.stress.sim <- function(chart,
                         stress.init = 0.0){
  #' Simulates the Stress through types
  #' 
  #' @description 
  #' 
  #' @param chart Chart generated by `f.stress.mapper`
  #' @param stress.init The **numeric** of 'stress' to 
  #' initialize the simulation with
   
  require(magrittr)
  require(dplyr)
  require(Rcpp)
  
  Rcpp::sourceCpp("src/cpp/stress_sim.cpp")
  
  # Allocate columns in advance
  chart %<>% 
    arrange(offsets)
  
  "Chart Frame is used to fill in those missing values 
  generated by columns on different offsets.
  
  This is used to do a OUTER JOIN to each key groups,
  hence you get NA data on those rows that shouldn't
  have data."
  chart.frame <- data.frame(offsets=unique(chart$offsets))
  
  # We will be looping through the chart by key
  chart.k.split <- split(x = chart, f = chart$keys)
  for (key in 1:length(chart.k.split)){
    chart.k <- chart.k.split[[key]]
    chart.k %<>%
      merge(chart.frame, by='offsets', all=T) %>% 
      mutate(is.spike = !is.na(types))
    
    chart.k.split[[key]] <- simulate_key(
      chart.k$offsets,
      chart.k$types
    )
  
  }
  
  # Join charts of different keys into one
  chart <- bind_rows(chart.k.split)
  return(chart)
}

# Some test data
# chart <- data.frame(keys = c(1,2,3,4),
#                     types = c('note', 'lnoteh', 'lnotel', 'note'),
#                     offsets = c(10,20,30,40))
# 
# df.mapping <- data.frame(types = c('note', 'lnoteh', 'lnotel'),
#                          adds = c(50,50,25),
#                          mults = c(1.1, 1.1, 1.03))
# 
# 
# f.spike <- function(stress, args){
#   return((stress + args$adds) * args$mults)
# }
# f.decay <- function(stress, duration){
#   return(stress / (2 ** duration))
# }
