f.stress.mapper.tmplt <-
  data.frame(types = c("note", "lnoteh", "lnotel"))

f.stress.mapper <- function(chart, df.map){
  #' Maps custom arguments to the chart specific to the type
  #' 
  #' @description 
  #' All data.frames for df.map must be based on
  #' f.stress.mapper.tmplt.
  #' 
  #' @param chart Chart generated by f.chart.parse
  #' @param df.map A data.frame to be used by the mapper.
  #' Must include "types" as a column.
  #' 
  #' "types" must include "note", "lnoteh", "lnotel".
  #' 
  #' @return Returns the mapped chart
  
  return(merge(chart, df.map, by="types"))
}